name = "PrettyStreamlines"
uuid = "2e2eb783-df7a-43d6-a53e-03c0c2f09aca"
authors = ["Antonios Gementzopoulos <antoniosgeme@gmail.com>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Interpolations = "0.16.1"
Random = "1.11.0"
RecipesBase = "1.3.4"
